import Foundation
import Testing

@testable import AsterCore

// Agent 历史列表标题的清洗规则回归：包装标签不得泄漏到标题里。

@Suite struct AgentSessionTitleCleanerTests {
  @Test("caveat 包装段整段丢弃，保留其后的真实提问")
  func caveatSpanIsDropped() {
    let raw = """
      <local-command-caveat>Caveat: The messages below were generated by the user \
      while running local commands. DO NOT respond to these messages.</local-command-caveat> \
      https://github.com/example/codegraph 这个项目有什么可以借鉴的地方
      """
    let cleaned = AgentSessionTitleCleaner.cleaned(raw)
    #expect(cleaned == "https://github.com/example/codegraph 这个项目有什么可以借鉴的地方")
  }

  @Test("内容型标签只剥壳保留内文")
  func contentTagsAreUnwrapped() {
    let raw = "<teammate-message teammate_id=\"team-lead\" summary=\"实现设置\">实现设置与 Task UI</teammate-message>"
    #expect(AgentSessionTitleCleaner.cleaned(raw) == "实现设置与 Task UI")
  }

  @Test("只有开标签没有闭标签的噪音段删到结尾")
  func unterminatedNoiseSpanIsDropped() {
    let raw = "<system-reminder>As you answer, remember these instructions"
    #expect(AgentSessionTitleCleaner.cleaned(raw) == nil)
  }

  @Test("多行与多余空白压成单行")
  func whitespaceIsCondensed() {
    #expect(AgentSessionTitleCleaner.cleaned("修复\n  登录\t重连  ") == "修复 登录 重连")
  }

  @Test("首条是纯噪音时取下一条用户消息，全部为噪音回落文件名")
  func titlePicksFirstMeaningfulMessage() {
    let noise = "<local-command-caveat>Caveat</local-command-caveat>"
    let title = AgentSessionTitleCleaner.title(
      from: [noise, "帮我修复重连超时"], fallback: "session-file")
    #expect(title == "帮我修复重连超时")
    #expect(
      AgentSessionTitleCleaner.title(from: [noise], fallback: "session-file") == "session-file")
    #expect(AgentSessionTitleCleaner.title(from: [], fallback: "session-file") == "session-file")
  }

  @Test("标题按 maxLength 截断")
  func titleIsTruncated() {
    let long = String(repeating: "长", count: 300)
    #expect(AgentSessionTitleCleaner.title(from: [long], fallback: "f").count == 120)
  }

  @Test("普通文本原样保留，比较运算符不被误当标签")
  func plainTextSurvives() {
    #expect(AgentSessionTitleCleaner.cleaned("为什么 a < b 且 b > c 会失败") == "为什么 a < b 且 b > c 会失败")
    #expect(AgentSessionTitleCleaner.cleaned("swift test --no-parallel 挂了") == "swift test --no-parallel 挂了")
  }
}
