// Generated by SessionRuntime/scripts/build-protocol.py. Do not edit.
import Foundation

public enum SessionOperationScope: String, Codable, Sendable { case session, registry, bootstrap }
public struct SessionOperationMetadata: Sendable {
  public let scope: SessionOperationScope
  public let capability: String?
  public let requiresRevision: Bool
  public let requiresLease: Bool
  public let requiresControlSequence: Bool
  public let requiresCreatedAt: Bool
}

public enum SessionOperationKind: String, Codable, CaseIterable, Sendable {
  case healthCheck = "health.check"
  case sessionList = "session.list"
  case sessionCreate = "session.create"
  case sessionAttach = "session.attach"
  case sessionStop = "session.stop"
  case sessionDelete = "session.delete"
  case sessionSnapshot = "session.snapshot"
  case sessionSettingsGet = "session.settings.get"
  case sessionSettingsUpdate = "session.settings.update"
  case sessionRestore = "session.restore"
  case workspaceList = "workspace.list"
  case workspaceCreate = "workspace.create"
  case workspaceUpdate = "workspace.update"
  case workspaceClose = "workspace.close"
  case tabCreate = "tab.create"
  case tabUpdate = "tab.update"
  case tabClose = "tab.close"
  case paneSplit = "pane.split"
  case paneUpdate = "pane.update"
  case paneClose = "pane.close"
  case terminalCreate = "terminal.create"
  case terminalList = "terminal.list"
  case terminalAttach = "terminal.attach"
  case terminalObserve = "terminal.observe"
  case terminalControl = "terminal.control"
  case terminalRelease = "terminal.release"
  case terminalTerminate = "terminal.terminate"
  case surfaceSubscribe = "surface.subscribe"
  case surfaceUnsubscribe = "surface.unsubscribe"
  case surfaceSnapshot = "surface.snapshot"
  case agentList = "agent.list"
  case agentReport = "agent.report"
  case agentExplain = "agent.explain"
  case agentRename = "agent.rename"
  case agentAcknowledge = "agent.acknowledge"
  case uploadBegin = "upload.begin"
  case uploadChunk = "upload.chunk"
  case uploadCommit = "upload.commit"
  case uploadAbort = "upload.abort"
  case uploadClear = "upload.clear"
  case configGet = "config.get"
  case configReload = "config.reload"
  case customCommandList = "custom_command.list"
  case customCommandRun = "custom_command.run"
  case integrationList = "integration.list"
  case integrationInstall = "integration.install"
  case integrationRemove = "integration.remove"
  case serverPrepare = "server.prepare"
  case serverStatus = "server.status"
  case serverStop = "server.stop"
  case serverReplace = "server.replace"
  case serverHandoff = "server.handoff"
  case requestStatus = "request.status"
  case uploadStatus = "upload.status"
  case serverOperationStatus = "server.operation_status"
  public var metadata: SessionOperationMetadata {
    switch self {
    case .healthCheck: .init(scope: .session, capability: "health_check", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .sessionList: .init(scope: .registry, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .sessionCreate: .init(scope: .registry, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .sessionAttach: .init(scope: .registry, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .sessionStop: .init(scope: .registry, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .sessionDelete: .init(scope: .registry, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .sessionSnapshot: .init(scope: .session, capability: "session_snapshot", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .sessionSettingsGet: .init(scope: .session, capability: "session_settings", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .sessionSettingsUpdate: .init(scope: .session, capability: "session_settings", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .sessionRestore: .init(scope: .session, capability: "session_restore", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .workspaceList: .init(scope: .session, capability: "session_snapshot", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .workspaceCreate: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .workspaceUpdate: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .workspaceClose: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .tabCreate: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .tabUpdate: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .tabClose: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .paneSplit: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .paneUpdate: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .paneClose: .init(scope: .session, capability: "workspace_mutation", requiresRevision: true, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .terminalCreate: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .terminalList: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .terminalAttach: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .terminalObserve: .init(scope: .session, capability: "terminal_observe", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .terminalControl: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: true, requiresControlSequence: true, requiresCreatedAt: false)
    case .terminalRelease: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .terminalTerminate: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: true)
    case .surfaceSubscribe: .init(scope: .session, capability: "surface_interest", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .surfaceUnsubscribe: .init(scope: .session, capability: "surface_interest", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .surfaceSnapshot: .init(scope: .session, capability: "surface_interest", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .agentList: .init(scope: .session, capability: "agent_state", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .agentReport: .init(scope: .session, capability: "agent_state", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .agentExplain: .init(scope: .session, capability: "agent_state", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .agentRename: .init(scope: .session, capability: "agent_state", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .agentAcknowledge: .init(scope: .session, capability: "agent_state", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .uploadBegin: .init(scope: .session, capability: "image_upload", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .uploadChunk: .init(scope: .session, capability: "image_upload", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .uploadCommit: .init(scope: .session, capability: "image_upload", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .uploadAbort: .init(scope: .session, capability: "image_upload", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .uploadClear: .init(scope: .session, capability: "image_upload", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .configGet: .init(scope: .session, capability: "server_config", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .configReload: .init(scope: .session, capability: "server_config", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .customCommandList: .init(scope: .session, capability: "custom_commands", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .customCommandRun: .init(scope: .session, capability: "custom_commands", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .integrationList: .init(scope: .session, capability: "agent_integration", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .integrationInstall: .init(scope: .session, capability: "agent_integration", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .integrationRemove: .init(scope: .session, capability: "agent_integration", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .serverPrepare: .init(scope: .bootstrap, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .serverStatus: .init(scope: .session, capability: "health_check", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .serverStop: .init(scope: .session, capability: "server_lifecycle", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .serverReplace: .init(scope: .session, capability: "server_replace", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .serverHandoff: .init(scope: .session, capability: "live_handoff", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .requestStatus: .init(scope: .session, capability: "terminal_control", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .uploadStatus: .init(scope: .session, capability: "image_upload", requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    case .serverOperationStatus: .init(scope: .registry, capability: nil, requiresRevision: false, requiresLease: false, requiresControlSequence: false, requiresCreatedAt: false)
    }
  }
}
