import AppKit
import AsterCore

/// 系统剪贴板的变更追踪：为终端提示符上的「剪贴板建议」提供尚未被消费的剪贴板文本。
///
/// macOS 不发布剪贴板变更通知，只能比较 `NSPasteboard.changeCount`。这里刻意不用定时器
/// 轮询：建议只在「应用重新激活」「新提示符就绪」「Aster 自己写了剪贴板」这三个时刻才
/// 有意义，由调用方在这三处拉取即可，省掉一个常驻定时器。
///
/// 实例全局共享（`shared`），因此「已接受或已忽略」的判定跨 Pane、跨窗口生效：在一个
/// Pane 里用过或忽略过的内容，不会再到别的 Pane 上重复弹一次。
@MainActor
final class ClipboardSuggestionMonitor {
  static let shared = ClipboardSuggestionMonitor()

  /// Aster 自己写入系统剪贴板后广播。终端内「选中即复制」不经过应用切换，也不产生
  /// OSC 133，没有这条通知，用户在当前 Pane 复制完就再也等不到建议。
  static let clipboardDidChangeLocally = Notification.Name("aster.clipboard-suggestion.changed")

  /// 密码管理器与临时内容的通用标记类型。这些内容一旦画成 ghost 就会出现在截屏、
  /// 录屏和旁人的视线里，必须整条跳过，而不是提示后再依赖用户去关。
  private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ]

  private let pasteboard: NSPasteboard
  private var consumedChangeCount: Int

  /// - Parameter pasteboard: 默认使用系统剪贴板；测试注入具名 pasteboard 以免污染用户环境。
  init(pasteboard: NSPasteboard = .general) {
    self.pasteboard = pasteboard
    // 启动时剪贴板里已有的内容不是「用户刚复制的」，视为已消费：否则每次开 Aster，
    // 第一个提示符都会弹出一条可能是几小时前复制的陈旧建议。
    consumedChangeCount = pasteboard.changeCount
  }

  /// 通知各 Pane 重新计算建议。Aster 自己的复制出口调用。
  static func noteLocalChange() {
    NotificationCenter.default.post(name: clipboardDidChangeLocally, object: nil)
  }

  /// 尚未被接受或忽略的剪贴板文本；没有可提示的新内容时返回 nil。
  func pendingText() -> String? {
    let current = pasteboard.changeCount
    guard current != consumedChangeCount else { return nil }
    // 先看类型列表再取内容：Universal Clipboard 的远端条目在真正读取时才会同步拉取，
    // 可能阻塞主线程数百毫秒，而这里处在每次候选刷新的热路径上。
    let types = Set(pasteboard.types ?? [])
    guard types.isDisjoint(with: Self.concealedTypes), types.contains(.string),
      let text = pasteboard.string(forType: .string)
    else {
      // 图片、文件、密码等永远不会成为命令行建议；直接消费掉，避免此后每个提示符
      // 都重新检查一次同样无用的剪贴板。
      consumedChangeCount = current
      return nil
    }
    return text
  }

  /// 标记当前剪贴板内容已被接受或忽略，同一份内容不再提示。
  func consume() {
    consumedChangeCount = pasteboard.changeCount
  }
}
